package com.baizhi.dao.original;

import com.baizhi.entity.original.Student;
import com.baizhi.entity.original.StudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    int insert(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    int insertSelective(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    Student selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    int updateByExampleSelective(@Param("row") Student row, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    int updateByExample(@Param("row") Student row, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    int updateByPrimaryKeySelective(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Mar 11 16:32:07 JST 2024
     */
    int updateByPrimaryKey(Student row);
}