server:
  port: 9999
  servlet:
    context-path: /ems-thymeleaf

# spring相关配置 datasource数据源  thymeleaf 模板引擎
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/,file:${upload.dir} #暴露哪些资源可以通过项目名访问
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

# mybatis配置
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity

# 日志配置
logging:
  level:
    root: info
    com.baizhi: debug
    org.mybatis.generator: debug

# 指定文件上传位置
photo:
  file:
#    dir: /Users/user/Documents/file/photo
    dir: C:\work\file\photo
